# ============================================
# Wisdom Index Unified Configuration
# ============================================

# -------- Output --------
output:
  csv_path: "harvest_output.csv"

# -------- Global Filters --------
require_business_context: true
business_hits_required: 1
require_imperative_or_rule: true
min_desc_chars: 60
max_desc_chars: 260

# -------- Keyword Anchors (Tacit Signals) --------
keywords:
  # Tacit signalers
  - workaround
  - rule_of_thumb
  - lesson_learned
  - pro_tip
  - checklist
  - gotcha
  - trick_i_learned
  - protip
  - secret_trick
  - my_secret_trick
  - my_secret_tip
  - my_secret_hack
  - my_secret_hack
  

# -------- Industry Modifiers --------
industry_modifiers:
  - SaaS
  - Finance
  - Consulting
  - Manufacturing
  - HR
  - Transportation
  - Telecommunications
  - Healthcare
  - Hospitality
  - Retail
  - Logistics
  - Marketing
  - IT
  - Legal
  - Education
# -------- Focus (Optional) --------
focus_industry: ""
focus_function: ""
focus_use_case: ""

# ============================================
# Source Toggles
# ============================================
sources:
  stackexchange: false
  github: false
  medium: false
  reddit: true

# ============================================
# Medium Settings
# ============================================
medium:
  tags:
    - best_practice

  harvest:
    min_claps: 10
    limit: 80
    time_filter: "year"
    throttle_sec: 0.5

# ============================================
# Reddit Settings
# ============================================
reddit:
  subreddits:
    - askreddit
    - entrepreneur
    - smallbusiness
    - startup
    - humanresources
    - fatbusiness
    - csuite

  harvest:
    search_strategy: "auto"
    limit: 30
    time_filter: "month"
    sort: "top"
    scan_comments: true
    per_thread_comment_limit: 5
    min_post_score: 5
    min_comment_score: 5
    throttle_sec: 0.7

    # Filters for better signal ↓
    comment_min_chars: 120
    comment_max_chars: 1200
    require_keyword_in_comment: true
    comment_patterns:
      - "^do\\b|^don’t\\b|^avoid\\b|^always\\b|^never\\b|^use\\b|^make sure\\b"
      - "\\b(because|so that|reason|works when|avoid this)\\b"



# ============================================
# StackExchange Settings
# ============================================
stackexchange:
  api_key: ""  # Optional
  sites:
    - workplace
  harvest:
    mode: "auto"                 # auto | api | html
    answered_only: true
    min_score: 2
    limit_per_site: 20
    time_filter: "year"
    impose_throttling: true
    throttle_sec: 3.0

# ============================================
# GitHub Settings
# ============================================
github:
  repos:
    - apache/airflow
    - pandas-dev/pandas
    - kubernetes/kubernetes
    - grafana/grafana
    - hashicorp/terraform
    - microsoft/azure-docs
  harvest:
    search_in: ["issues", "discussions", "pulls"]
    states: ["open", "closed"]
    label_includes:
      - postmortem
      - retrospective
      - incident
      - regression
      - best-practice
    comment_scan: true
    min_comment_len: 120
    max_threads_per_repo: 120
    throttle_sec: 1.0
